name: CI Workflow of My Application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: build app
        run: npm run build   

  build-and-test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Checkout Selenium Tests
        uses: actions/checkout@v4
        with:
          repository: indika02/studentautomation
          path: selenium-tests  

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 24

      - name: Install Allure Commandline
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      - name: Build Selenium tests with Maven
        run: |
          cd selenium-tests
          mvn clean install   

      - name: Run Selenium tests    
        run: |
          cd selenium-tests
          mvn clean test

      - name: Generate Allure Report
        run: allure generate selenium-tests/allure-results -o selenium-tests/allure-report/ReportFiles --clean

      - name: open Allure Report
        run: |
          cd selenium-tests/allure-report/ReportFiles
          allure open .
                
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v6
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./allure-report
      
      - name: Send Test Report to email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          subject: Final Test Report
          to: indikasenarathna356@gmail.com
          from: ${{ secrets.EMAIL }}
          content_type: text/html
          body: |
            Selenium test report attached.
          attachments: selenium-tests/target/reports/cucumber-html-reports/test.html

  # Container:
  #     runs-on: ubuntu-latest
  #     needs: Test
  #     steps:
  #       - name: Checkout repository
  #         uses: actions/checkout@v4

  #       - name: Build Docker image
  #         run: docker build -t sms:latest .

  #       - name: Run Docker container
  #         run: docker run -p 8080:8080 sms:latest
                    