name: CI Workflow of My Application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: build app
        run: npm run build   

  Test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout Selenium Tests
        uses: actions/checkout@v4
        with:
          repository: indika02/studentautomation
          path: selenium-tests

      - name: Set up java
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: set up and Run Selenium test dependencies
        run: |
          cd selenium-tests
          mvn clean  install -e 

      - name: Generate Cucumber HTML report
        run: |
          cd selenium-tests
          mvn net.masterthought:maven-cucumber-reporting:generate    

      - name: Send Test Report to email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          subject: Final Test Report
          to: indikasenarathna356@gmail.com
          from: ${{ secrets.EMAIL }}
          content_type: text/html
          body: |
            Selenium test report attached.
            attachments: selenium-tests/target/cucumber-reports/cucumber-html-reports/test.html

  # Container:
  #     runs-on: ubuntu-latest
  #     needs: Test
  #     steps:
  #       - name: Checkout repository
  #         uses: actions/checkout@v4

  #       - name: Build Docker image
  #         run: docker build -t sms:latest .

  #       - name: Run Docker container
  #         run: docker run -p 8080:8080 sms:latest
                    